[package]
org = "qaadir"
name = "gemini"
version = "3.5.5"
distribution = "2201.13.1"
authors = ["Qaadir"]
keywords = ["Gemini", "AI", "Google", "Rag", "Agent", "llm"]
license = ["Apache-2.0"]
icon = "icon.png"
repository = "https://github.com/AbQaadir/module-ballerinax-gemini"
